# Generated by Django 4.2 on 2023-04-27 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcard',
            name='card_is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientcard',
            name='table_number',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
