# Generated by Django 4.2 on 2023-04-27 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_menuitem_photo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MenuCategory',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='MenuItem',
            new_name='Item',
        ),
    ]
