# Generated by Django 4.2 on 2023-04-28 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_alter_item_ingredients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='ingredients',
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
