# Generated by Django 4.2 on 2023-04-28 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_remove_item_ingredients_delete_ingredient'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name', 'visible'], 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-category', 'name', 'visible']},
        ),
    ]
