# Generated by Django 4.2 on 2023-05-18 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0012_alter_category_section_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='origin_country_code',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
