# Generated by Django 4.2 on 2023-05-21 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0014_restaurant_menu_category_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
